<?php

namespace Welinkeo\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderlistRepository extends EntityRepository
{
}
