<?php

namespace Welinkeo\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Volume_CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Volume_CategoryRepository extends EntityRepository
{
}
